spring:
  profiles:
    active:
    -dev
 
---
spring:
  profiles: dev
  application:
    name: lgzservicecloud-config-lgz-dev
     
---
spring:
  profiles: test
  application:
    name: lgzservicecloud-config-lgz-test