spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: lgzservicecloud-config-lgz-dev-hello
---
spring:
  profiles: test
  application:
    name: lgzservicecloud-config-lgz-test