spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: lgzservicecloud-config-client
eureka:
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    service-url:
      defaultZone: http://eureka7001:7001/eureka
---
server:
  port: 8202
spring:
  profiles: dev
  application:
    name: lgzservicecloud-config-client
eureka:
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    service-url:
      defaultZone: http://eureka7001:7001/eureka